<?php

namespace AppBundle\Repository;

/**
 * ActualiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActualiteRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Liste decroissante des actualités
     * Backend_actulaite_index
     */
    public function findList($statut = null, $limit = null, $offset = null)
    {
        if ($statut){
            if ($limit){
                if (!$offset){$offset = 0;}
                return $this->QueryList()->where('a.statut = 1')
                                         ->setFirstResult($offset)
                                         ->setMaxResults($limit)
                                         ->getQuery()->getResult()
                    ;
            }else{
                return $this->QueryList()->where('a.statut = 1')->getQuery()->getResult();
            }
        }else{
            return $this->QueryList()->getQuery()->getResult();
        }
    }

    /**
     * requete de liste decroissante
     */
    protected function QueryList()
    {
        return $this->createQueryBuilder('a')->orderBy('a.id', 'DESC');
    }
}
