<?php

namespace AppBundle\Repository;

/**
 * ArtisteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtisteRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Liste alphabetique des artistes
     */
    public function findList()
    {
        return $this->createQueryBuilder('a')
                    ->orderBy('a.pseudonyme', 'ASC')
                    ->getQuery()->getResult()
            ;
    }
}
