<?php

namespace AppBundle\Repository;

/**
 * BuzzRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuzzRepository extends \Doctrine\ORM\EntityRepository
{
}
