<?php

namespace AppBundle\Repository;

/**
 * CandidatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CandidatRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAutresCandidats($id)
    {
        return $this->createQueryBuilder('c')
                    ->where('c.id <> :id')
                    ->orderBy('c.total', 'DESC')
                    ->addOrderBy('c.code', 'ASC')
                    ->setParameter('id', $id)
                    ->getQuery()->getResult()
            ;
    }

    public function findList()
    {
        return $this->createQueryBuilder('c')
                    ->orderBy('c.total', 'DESC')
                    ->addOrderBy('c.code', 'ASC')
                    ->getQuery()->getResult()
                ;
    }
}
