<?php

namespace AppBundle\Repository;

/**
 * ChansonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChansonRepository extends \Doctrine\ORM\EntityRepository
{
}
