<?php

namespace AppBundle\Repository;

/**
 * ConcoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConcoursRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Liste des concours
     */
    public function Liste()
    {
        return $this->createQueryBuilder('c')
                    ->orderBy('c.titre', 'ASC')
            ;
    }
}
