<?php

namespace AppBundle\Repository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Liste des events par ordre decroissant
     */
    public function findList()
    {
        return $this->createQueryBuilder('e')
                    ->orderBy('e.id', 'DESC')
                    ->getQuery()->getResult()
            ;
    }
}
