<?php

namespace AppBundle\Repository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Liste des events par ordre decroissant
     */
    public function findList()
    {
        return $this->createQueryBuilder('e')
                    ->orderBy('e.id', 'DESC')
                    ->getQuery()->getResult()
            ;
    }

    /**
     * Liste des events par date
     */
    public function findListEvent($limit = null)
    {
        if ($limit){
            return $this->createQueryBuilder('e')
                ->where('e.dateEvent > :date')
                ->orderBy('e.dateEvent', 'ASC')
                ->setFirstResult(0)
                ->setMaxResults($limit)
                ->setParameter('date', date('Y-m-d', time()))
                ->getQuery()->getResult()
                ;
        }else{
            return $this->createQueryBuilder('e')
                ->where('e.dateEvent > :date')
                ->orderBy('e.dateEvent', 'ASC')
                ->setParameter('date', date('Y-m-d', time()))
                ->getQuery()->getResult()
                ;
        }
    }
}
