<?php

namespace AppBundle\Repository;

/**
 * ReglementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReglementRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     *
     */
    public function findOnly($slug)
    {
        return $this->createQueryBuilder('r')->where('r.slug = :slug')->setParameter('slug', $slug);
    }
}
